export const ErrorCodes = {
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  FB_API_ERROR: 'FB_API_ERROR',
  CAMPAIGN_NOT_FOUND: 'CAMPAIGN_NOT_FOUND',
  RULE_EVALUATION_FAILED: 'RULE_EVALUATION_FAILED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
} as const;
