import { Controller, Get, Param, Query, Res, UseGuards, Req } from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { Response } from 'express';
import { ReportsService } from './reports.service';

@Controller('reports')
@UseGuards(AuthGuard('jwt'))
export class ReportsController {
  constructor(private readonly reportsService: ReportsService) {}

  @Get('campaigns/:id/data')
  async getCampaignData(@Param('id') id: string, @Req() req: any) {
    return this.reportsService.getCampaignReportData(id, req.user.id);
  }

  @Get('accounts/:id/data')
  async getAccountData(@Param('id') id: string, @Req() req: any) {
    return this.reportsService.getAccountReportData(id, req.user.id);
  }

  @Get('campaigns/:id/excel')
  async exportCampaignExcel(@Param('id') id: string, @Req() req: any, @Res() res: Response) {
    const data = await this.reportsService.getCampaignReportData(id, req.user.id);
    const c = data.campaign;
    const s = data.summary;

    const header = 'Date,Impressions,Clicks,CTR%,CPC,CPM,Spend,Conversions';
    const rows = data.insights.map(i =>
      `${new Date(i.date).toISOString().slice(0, 10)},${i.impressions},${i.clicks},${i.ctr.toFixed(2)},${i.cpc.toFixed(2)},${i.cpm.toFixed(2)},${i.spend.toFixed(2)},${i.conversions}`
    );
    const csv = [header, ...rows].join('\n');

    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename="${c.name.replace(/[^a-zA-Z0-9]/g, '_')}_report.csv"`);
    res.send(csv);
  }

  @Get('campaigns/:id/html')
  async exportCampaignHtml(@Param('id') id: string, @Req() req: any, @Res() res: Response) {
    const data = await this.reportsService.getCampaignReportData(id, req.user.id);
    const c = data.campaign;
    const s = data.summary;

    const dailyRows = data.insights.map(i => {
      const d = new Date(i.date).toISOString().slice(0, 10);
      return `<tr><td>${d}</td><td>${i.impressions.toLocaleString()}</td><td>${i.clicks.toLocaleString()}</td><td>${i.ctr.toFixed(2)}%</td><td>${i.cpc.toFixed(2)}</td><td>${i.cpm.toFixed(2)}</td><td>${i.spend.toFixed(2)}</td><td>${i.conversions}</td></tr>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  body{font-family:Arial,sans-serif;padding:30px}
  h1{color:#1a1a2e;border-bottom:3px solid #3b82f6;padding-bottom:10px}
  .meta{color:#666;margin-bottom:20px}
  .stats{display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:10px;margin-bottom:30px}
  .card{background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:15px;text-align:center}
  .card .v{font-size:24px;font-weight:bold;color:#1e293b}
  .card .l{font-size:11px;color:#64748b;text-transform:uppercase;margin-top:4px}
  table{width:100%;border-collapse:collapse;font-size:12px}
  th{background:#3b82f6;color:white;padding:8px 10px;text-align:left}
  td{padding:6px 10px;border-bottom:1px solid #e2e8f0}
  tr:nth-child(even){background:#f8fafc}
  .f{margin-top:30px;font-size:11px;color:#94a3b8;text-align:center}
</style></head><body>
<h1>${c.name}</h1>
<div class="meta">Account: ${c.accountName} | Objective: ${c.objective} | Status: ${c.status} | Budget: ${c.currency} ${c.dailyBudget}/day</div>
<div class="stats">
  <div class="card"><div class="v">${s.impressions.toLocaleString()}</div><div class="l">Impressions</div></div>
  <div class="card"><div class="v">${s.clicks.toLocaleString()}</div><div class="l">Clicks</div></div>
  <div class="card"><div class="v">${data.ctr}%</div><div class="l">CTR</div></div>
  <div class="card"><div class="v">${c.currency} ${data.cpc}</div><div class="l">CPC</div></div>
  <div class="card"><div class="v">${c.currency} ${data.cpm}</div><div class="l">CPM</div></div>
  <div class="card"><div class="v">${c.currency} ${s.spend.toFixed(2)}</div><div class="l">Total Spend</div></div>
  <div class="card"><div class="v">${s.conversions}</div><div class="l">Conversions</div></div>
</div>
<h3>Daily Breakdown</h3>
<table><tr><th>Date</th><th>Impressions</th><th>Clicks</th><th>CTR%</th><th>CPC</th><th>CPM</th><th>Spend</th><th>Conv</th></tr>${dailyRows}</table>
<div class="f">Generated by FB Ads Platform &bull; ${new Date().toISOString().slice(0, 10)}</div>
</body></html>`;

    res.setHeader('Content-Type', 'text/html');
    res.setHeader('Content-Disposition', `attachment; filename="${c.name.replace(/[^a-zA-Z0-9]/g, '_')}_report.html"`);
    res.send(html);
  }
}
